resources:
    CoralMedia\Bundle\SecurityBundle\Entity\User:
        properties:
            id:
                identifier: true
        attributes:
            route_prefix: /security
            normalization_context:
                groups: [ 'user:read' ]
            denormalization_context:
                groups: [ 'user:write' ]